theme: jekyll-theme-minimal
title: Shenyang's homepage
description: I am a Research Associate at the Advanced Institute of Business, Tongji University. I received my Ph.D. from School of Management, Zhejiang University. 
