theme: jekyll-theme-minimal
title: Shenyang's homepage
description: I am an Assistant Professor at the Advanced Institute of Business, Tongji University. I received my Ph.D. from School of Management, Zhejiang University. 
Welcome to my website
